// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyap4HSx7K3lMF2hA2LVw6_EFhQQn4hOw',
    appId: '1:89084506071:web:e43484314ee19a66122592',
    messagingSenderId: '89084506071',
    projectId: 'enelsisapp',
    authDomain: 'enelsisapp.firebaseapp.com',
    storageBucket: 'enelsisapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmx6Fx44b_fntlkIt89ramvUocnC2MBnM',
    appId: '1:89084506071:android:0061b3c527151546122592',
    messagingSenderId: '89084506071',
    projectId: 'enelsisapp',
    storageBucket: 'enelsisapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz05mCh3I82jtFPxjtyxHcBF6GxmjFt5s',
    appId: '1:89084506071:ios:3c02c64a411a4c80122592',
    messagingSenderId: '89084506071',
    projectId: 'enelsisapp',
    storageBucket: 'enelsisapp.appspot.com',
    iosClientId: '89084506071-7u7q7u6n17fbdetg94nm0lfi0qdq8h49.apps.googleusercontent.com',
    iosBundleId: 'com.example.enelsisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz05mCh3I82jtFPxjtyxHcBF6GxmjFt5s',
    appId: '1:89084506071:ios:26448cbceafd02a7122592',
    messagingSenderId: '89084506071',
    projectId: 'enelsisapp',
    storageBucket: 'enelsisapp.appspot.com',
    iosClientId: '89084506071-m5gja5fje70775s3p9mnjb40vtj9h962.apps.googleusercontent.com',
    iosBundleId: 'com.example.enelsisApp.RunnerTests',
  );
}
